### ISSUE TITLE
package signing

### ISSUE THREAD

**Issue by mrash** [jp-bennett/fwknop-gui#11]
Would it be possible to publish SHA-256 digests and GPG signatures of the UI packages available on the download page?:

https://incomsystems.biz/fwknop-gui/downloads.html

I can sign the packages with the cipherdyne software signing key as well if you like.

**Comment by jp-bennett** [comment]
The 1.3 release is up, with the release files signed using the cipherdyne key.  Additionally, the Windows and mac binaries include a valid code signing key issued to Incom Systems.
Is the public half of that key hosted somewhere on cipherdyne.org that I could link to?

**Comment by mrash** [comment]
Awesome. Yes, the public key is available here:

https://www.cipherdyne.org/contact.html
