### ISSUE TITLE
QR code is truncated on Fedora

### ISSUE THREAD

**Issue by Jakuje** [jp-bennett/fwknop-gui#22]
I was playing around with your GUI and found out that the QR code is truncated and does not show all the code in the pop-up window. Attaching screenshot from Fedora 24 (default Gnome Shell, Wayland)

![screenshot from 2016-08-30 16-44-38](https://cloud.githubusercontent.com/assets/2694489/18093727/269d39e4-6ed1-11e6-943a-fe294e7fb071.png)

Let me know if there is some more information you need to resolve this problem. Seems like [the size](https://github.com/jp-bennett/fwknop-gui/blob/master/qr_export.cpp#L71) is not enough to fit the bold corners?

**Comment by jp-bennett** [comment]
I will go check it out and get it fixed, thanks for the report!  I run KDE on my desktop, which is probably why I never saw this behavior.

**Comment by jp-bennett** [comment]
I have this fixed in trunk, just need to test on all the supported platforms, and then I'll do a point release and get it updated in Fedora.

**Comment by Jakuje** [comment]
Verified that it works fine with the 1.3.1 in my Fedora 24 (the QR is basically empty since I didn't add the key):
![screenshot from 2016-09-05 13-11-06](https://cloud.githubusercontent.com/assets/2694489/18246192/5f2aee62-736a-11e6-8acf-e7eae78f8ec6.png)

**Comment by jp-bennett** [comment]
Fixed in release 1.3.1
