### ISSUE TITLE
Win10 Error: Could notsend knock: Error sending.

### ISSUE THREAD

**Issue by moondog13** [jp-bennett/fwknop-gui#9]
When I attempt to send a knock from my Windows 10 virtual machine I initially receive no feedback after clicking the "send knock" button however if I try to send another knock the program ceases to be responsive which I kill off with the task manager after a bit. If I only try to send one knock and leave the program sitting after a few minutes I receive a message box stating, "Could not send knock: Error sending."

I have tried running it both as my user and as the Administrator, and each of those with and without the Windows firewall enabled. I can see entries in the Windows Application logs indicating the application stopped interacting with windows and others indicating it was closed. Here are the details as copied/pasted from a hang entry:

- System 

  - Provider 

   [ Name]  Application Hang 
 
  - EventID 1002 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 101 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2015-10-26T22:42:34.000000000Z 
 
   EventRecordID 593 
 
   Channel Application 
 
   Computer DESKTOP-B0MO4ES 
 
   Security 
 

- EventData 

   fwknop-gui.exe 
   0.0.0.0 
   148c 
   01d1103f82ed95d6 
   4294967295 
   C:\Program Files (x86)\fwknop-gui\fwknop-gui.exe 
   d889756c-7c32-11e5-9bc8-5254003e724f 
    
    
   54006F00700020006C006500760065006C002000770069006E0064006F0077002000690073002000690064006C00650000000000 

--------------------------------------------------------------------------------

Binary data:

In Words

0000: 006F0054 00200070 0065006C 00650076 
0010: 0020006C 00690077 0064006E 0077006F 
0020: 00690020 00200073 00640069 0065006C 
0030: 00000000    

In Bytes

0000: 54 00 6F 00 70 00 20 00   T.o.p. .
0008: 6C 00 65 00 76 00 65 00   l.e.v.e.
0010: 6C 00 20 00 77 00 69 00   l. .w.i.
0018: 6E 00 64 00 6F 00 77 00   n.d.o.w.
0020: 20 00 69 00 73 00 20 00    .i.s. .
0028: 69 00 64 00 6C 00 65 00   i.d.l.e.
0030: 00 00 00 00               ....

Please advise.

**Comment by oneru** [comment]
@moondog13 I'll look into this issue as soon as I can.  Thanks for reporting!

**Comment by jp-bennett** [comment]
Closing for now.  Please re-open if it's still a problem in the 1.3 beta1 release, available at https://incomsystems.biz/fwknop-gui/downloads.php
